### ISSUE TITLE
Activerow->update failing when ds_row is missing a table name

### ISSUE THREAD

**Issue by bfad** [zeroloop/ds#14]
If I call `activerow->update` on an object that has been created by passing a `ds_row` from a SQL query to the creator method it fails because it doesn't have a table name.

For example, this code fails:

```lasso
define tt_ticket => type { parent activerow

    public onCreate(...)         => ..onCreate(:(:tag(db_is_tickettrack + '.tickets')) + #rest)
    public onCreate(id::integer) => tt_ticket_get(#id)
}

define tt_ticket_get(id::integer) => {
    local(sql) ="SELECT * FROM tickets t WHERE t.id=" + #id
    return ds('is_tickettrack')->sql(#sql)->rows(::tt_ticket)->first
}

tt_ticket(430)->update('status'='closed')
```

**Comment by Ke-** [comment]
Hello Brad,

This is not a bug, at no point are you specifying the table any where via this route (you're oncreate definition is being skipped). I would recommend an approach similar to the below:

```lasso
define tt_ticket => type { parent activerow
    public ds => ds(db_is_tickettrack,'changes')
    public onCreate(...)         => ..onCreate(:#rest)
    public onCreate(id::integer) => tt_ticket_get(#id)
}
```

In this scenario if the row supplied is unaware of the table it belongs to (normally caused by omitting the table when retrieving the row) activerow will use the table specified within the type (latest release).

Alternatively simply specify the table somewhere along the chain, ie.

```lasso
    return ds('is_tickettrack','tickets')->sql(#sql)->rows(::tt_ticket)->first
```
Or even this:

```lasso
    // Table specified after retrieving rows (has it's uses)
    return ds('is_tickettrack')->sql(#sql)->table(::tickets)->rows(::tt_ticket)->first 
```

Hope that helps.

Ke

**Comment by bfad** [comment]
Why is my `onCreate` method being skipped? The point of that method is to initialize the object, so if you're just calling `::tt_ticket->getType` and then stashing the `ds_row` into the "row" data attribute, I would say you're doing it wrong. The `activerow` type has an `onCreate` method that can take a `ds_row`, so if you instead called `\(::tt_ticket)(ds_row)` my `onCreate` method would be called and end up passing the `ds_row` to the `activerow` method and setting things up correctly.

Because `activerow` has the appropriate method already, changing `ds_result->rows(type::tag)` to actually call the creator method and initialize the type properly shouldn't break anything, it would be consistent with how object creation in Lasso is supposed to happen, and it sounds like it would also fix this issue.

**Comment by atpjd** [comment]
I just want to say thank you both for bringing your collective awesomeness
to the Lasso community.

**Comment by Ke-** [comment]
It doesn't skip oncreate; your catch all will be skipped as there is a matching signature with greater precedence:

```lasso
activerow->oncreate(::ds_row)
```

Activerow types are created using a ds_row as the parameter for oncreate when retrieved with the -->rows(::type) syntax. You can elicit alternative behaviour by using the ->rows(\type) syntax.

But your approach would still fail as there is no activerow(databasetable::tag,::ds_row) signature.

**Comment by bfad** [comment]
I now see - essentially you've figured out a way for a type's parent `onCreate` method to be called. I had tried defining a ds method before and it didn't work, but it looks like the latest update fixes that. Thanks for the explanation and the patch.
