### ISSUE TITLE
Insert Statement Columns not escaped

### ISSUE THREAD

**Issue by bfad** [zeroloop/ds#15]
This may be an issue in other place, but I just ran into the issue using `insert_statement`. You aren't wrapping column names in backticks which results in queries that are unable to run.

For example:
```lasso
ds->insert->into(::email_log)->addRow(map(::from='me@example.com'))->do
```

This will cause an error because the generated SQL doesn't wrap "from" in backticks.

**Comment by SteffanCline** [comment]
I wonder if this is what my issue is. I get this error consistently.
ds error: Unknown column '2' in 'field list'
I dumped my map to the screen to see if there was a field there by that name and nothing. Seems I can't add until this works. Is there a way to get an older version?

**Comment by Ke-** [comment]
@Brad, yes this was a design decision — only MySQL uses back ticks. I've added some logic to do so if the statement thinks it's working with MySQL.

@stephan, I suspect this is down to a change in behaviour from Lasso 9.2.x to Lasso 9.3, see: http://www.lassosoft.com/rhinotrac?id=7945 — Am not sure I will change this as it's something Lassosoft need to address. Regardless is this a different is to what Brad refers to, please raise another issue.
