### ISSUE TITLE
Broken add row with L9.3

### ISSUE THREAD

**Issue by SteffanCline** [zeroloop/ds#16]
I wonder if this is what my issue is. I get this error consistently.
ds error: Unknown column '2' in 'field list'
I dumped my map to the screen to see if there was a field there by that name and nothing. Seems I can't add until this works. Is there a way to get an older version?

->addrow really butchered my query.

INSERT INTO mhloans.applications (2,1,P,6,5,J,D,V,4,7,A,8,S,Y,3,R,M) VALUES ('0','2,9,2,2,2,2,2','h,h','7',NULL,'o,a,o','i,i','e','5,5,5,5','8,8','Z,f,Z','5,9','p','e','4,3','e','a')

The tick marks are there for me (I'm not sure how to style it right in here) but clearly those are not the fields.

Here is what I am handing off to ->addrow

map(address_length_mo = 2, address_length_yr = 2, app_address = 123 Easy St, app_city = Phoenix, app_dob1 = 6, app_dob2 = 5, app_dob3 = 1996, app_name_first = Joe, app_name_last = Dirt, app_name_mi = V, app_phone1 = 123, app_phone2 = 456, app_phone3 = 7890, app_ssn1 = 123, app_ssn2 = 45, app_ssn3 = 6789, app_state = AZ, app_unit = 123, app_zip = 85015, applying_status = Spouse, bankruptcy = Yes, bankruptcy_year = 20, best_number1 = 789, best_number2 = 123, best_number3 = 4567, best_time_call = Afternoon, coapp_dob1 = 7, coapp_first = Jane, coapp_homemaker = 1, coapp_last = Dirt, coapp_mi = V, coapp_ssn1 = 890, coapp_ssn2 = 12, coapp_ssn3 = 3456, email_address = joe@dirt.com, loantype = Refinance, marital_status = Married, previous_address = 456 Easy St, previous_city = Phoenix, previous_length_mo = 3, previous_length_yr = 33, previous_state = AZ, rate_credit = Very Good)

As far as demo code, above is the map and I am doing a simple add row to an existing table.

While this may be a 9.3 bug, given the current status of development there, can you build in a temporary work around? I can't even use DS at this point because of this. This has broken another site I went back to developing.

**Comment by Ke-** [comment]
Believe this has been resolved, was down to a signature clash.

**Comment by jolle-c** [comment]
When was the fix supplied? I can't see any code changes since April 20

**Comment by Ke-** [comment]
This was a signature issue in 9.3, the commit was in April at some point —
simply didn't close the issue.
